# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb1fb04262c09081285f7ea4845a4a4673b118d549182e03ca9757ff0fecbeb9b231423100d2493e763e04d5f98765d215d527ef0918e622af07e2ad9d9bc6cf

test:
  secret_key_base: 4ece3ab7f59f74b6dea2b80591d4eb55ee90ab8432cd679120325fac7c8bddbd0770b59084daab6abe33b3d1d8baa1bbbaf5a468bf7f80e69c451aa2c8ecc761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
